name: CI Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Install deps & run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: app_test
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 5s --health-timeout 5s --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/app_test
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Prisma Migrate (deploy)
        run: npx prisma migrate deploy

      - name: Run tests
        run: npm test -- --ci --reporters=default --reporters=jest-junit

      - name: Upload coverage
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
          if-no-files-found: ignore

      - name: JUnit report artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: junit.xml
          if-no-files-found: ignore
